version: '3.8'
services:
    app:
        container_name: 7learn
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - internal
        command: >
            sh -c '
                #php artisan migrate &&
                #php artisan db:seed &&
                #php artisan queue:work &&
                php artisan serve --host=0.0.0.0
            '
        ports:
            - "8000:8000"
        volumes:
            - ~/projects/7learn:/laravel
#        restart: always
        depends_on:
            - mysql

    mysql:
        container_name: db
        image: mysql:latest
        networks:
            - internal
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

    elasticsearch:
        container_name: elastic
        image: elasticsearch:8.12.2
        networks:
            - internal
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elastic_data:/usr/share/elasticsearch/data

networks:
    internal:
        driver: bridge

volumes:
    db_data:
    elastic_data:
